const productsData = [
  {
    id: 1,
    Name: "Long Rice",
    description: "Rice",
    price: 10,
    image: "../asset/cereals.png",
    category: "Cereals",
  },
  {
    id: 2,
    Name: "Rice",
    description: "Foreign Made Rice",
    price: 17,
    image: "../asset/cereals.png",
    category: "Cereals",
  },
  {
    id: 3,
    Name: "Iron Beans",
    description: "Beans",
    price: 12,
    image: "../asset/cereals.png",
    category: "Beans",
  },
  {
    id: 4,
    Name: "Cereal5",
    description: "Brewed Cereals",
    price: 8,
    image: "../asset/cereals.png",
    category: "Carbohydrate",
  },
  {
    id: 5,
    Name: "Corn flakes",
    description: "nice one corn flakes",
    price: 13,
    image: "../asset/cereals.png",
    category: "Cereals",
  },
  {
    id: 6,
    Name: "Golden Morn",
    description: "nice one golden morn",
    price: 12,
    image: "../asset/cereals.png",
    category: "Cereals",
  },
  {
    id: 7,
    Name: "Rice",
    description: "Foreign Made Rice",
    price: 40,
    image: "../asset/cereals.png",
    category: "Cereals",
  },
  {
    id: 8,
    Name: "Rice",
    description: "Foreign Made Rice",
    price: 50,
    image: "../asset/cereals.png",
    category: "Cereals",
  },
  {
    id: 9,
    Name: "Rice",
    description: "Foreign Made Rice",
    price: 50,
    image: "../asset/cereals.png",
    category: "Cereals",
  },
  {
    id: 10,
    Name: "Rice",
    description: "Foreign Made Rice",
    price: 50,
    image: "../asset/cereals.png",
    category: "Cereals",
  },
  {
    id: 11,
    Name: "Rice",
    description: "Foreign Made Rice",
    price: 50,
    image: "../asset/cereals.png",
    category: "Cereals",
  },
  {
    id: 12,
    Name: "Rice",
    description: "Foreign Made Rice",
    price: 50,
    image: "../asset/cereals.png",
    category: "Cereals",
  },
  {
    id: 1,
    Name: "Rice",
    description: "Foreign Made Rice",
    price: 10,
    image: "../asset/cereals.png",
    category: "Cereals",
  },
  {
    id: 2,
    Name: "Rice",
    description: "Foreign Made Rice",
    price: 17,
    image: "../asset/cereals.png",
    category: "Cereals",
  },
]