const productsData = [
  {
    id: 1,
    Name: "long Gown",
    description: "Gown",
    price: 14,
    image: "../asset/images.jpeg",
    category: "Gown",
  },
  {
    id: 2,
    Name: "Long Sleeve",
    description: "Shirt",
    price: 12,
    image: "../asset/download1.jpeg",
    category: "Shirt",
  },
  {
    id: 3,
    Name: "long Gown",
    description: "Gown",
    price: 17,
    image: "../asset/images.jpeg",
    category: "Gown",
  },
  {
    id: 4,
    Name: "Long Sleeve",
    description: "Shirt",
    price: 19,
    image: "../asset/download1.jpeg",
    category: "Shirt",
  },
  {
    id: 5,
    Name: "long Gown",
    description: "Gown",
    price: 10,
    image: "../asset/images.jpeg",
    category: "Gown",
  },
  {
    id: 6,
    Name: "Long Sleeve",
    description: "Shirt",
    price: 6,
    image: "../asset/download1.jpeg",
    category: "Shirt",
  },
  {
    id: 7,
    Name: "long Gown",
    description: "Gown",
    price: 11,
    image: "../asset/images.jpeg",
    category: "Gown",
  },
  {
    id: 8,
    Name: "Long Sleeve",
    description: "Shirt",
    price: 7,
    image: "../asset/download1.jpeg",
    category: "Shirt",
  },
  {
    id: 9,
    Name: "long Gown",
    description: "Gown",
    price: 13,
    image: "../asset/images.jpeg",
    category: "Gown",
  },
  {
    id: 10,
    Name: "Long Sleeve",
    description: "Shirt",
    price: 10,
    image: "../asset/download1.jpeg",
    category: "Shirt",
  },
  {
    id: 11,
    Name: "long Gown",
    description: "Gown",
    price: 19,
    image: "../asset/images.jpeg",
    category: "Gown",
  },
  {
    id: 12,
    Name: "Long Sleeve",
    description: "Shirt",
    price: 14,
    image: "../asset/download1.jpeg",
    category: "Shirt",
  },
  {
    id: 13,
    Name: "long Gown",
    description: "Gown",
    price: 15,
    image: "../asset/images.jpeg",
    category: "Gown",
  },
  {
    id: 14,
    Name: "Long Sleeve",
    description: "Shirt",
    price: 17,
    image: "../asset/download1.jpeg",
    category: "Shirt",
  },
  {
    id: 15,
    Name: "long Gown",
    description: "Gown",
    price: 17,
    image: "../asset/images.jpeg",
    category: "Gown",
  },
]